services:
  - type: web
    name: loja-lead2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: https://dpanpvimjgybiyjnuyzi.supabase.co
      - key: SUPABASE_KEY
        value: SUA_CHAVE_COMPLETA_AQUI
